### ISSUE TITLE
embedding network architecture

### ISSUE THREAD

**Issue by leekyungmoon** [clovaai/symmetrical-synthesis#4]
After average pooling the CNN features extracted from the googlenet, 

It looks like 'slim.conv2d' was used instead of a fully connected layer.

Then the code in this repository has a different architecture from the original embedding network.

Is this correct?

**Comment by geonm** [comment]
Hi @leekyungmoon 

It's a simple thing.

The 1x1 convolution layer works the same as the fully connected layer after GAP layer.

+ If we use 1x1 conv, the shape of batch tensor like:
`[batch_index, height, width, input_dims]` > GAP > `[batch_index, 1, 1, input_dims]` > 1x1 conv > `[batch_index, 1, 1, output_dims]` > squeeze > `[batch_index, output_dims]`

+ If we use the fully connected layer instead of 1x1 conv, the shape of batch tensor like:
`[batch_index, height, width, input_dims]` > GAP > `[batch_index, 1, 1, input_dims]` > squeeze > `[batch_index, input_dims]` > fully connected layer > `[batch_index, output_dims]`
